import matplotlib.pyplot as plt

# Define nodes with coordinates (x, y) and assigned colors
nodes = {
    "start": (0, 0, "green"),
    "gate_hell1": (2, 0, "red"),
    "gate_hell2": (3, 0, "red"),
    "gate_hell3": (4, 0, "red"),
    "gate_hell4": (5, 0, "red"),
    "gate_hell5": (6, 0, "red"),
    "maze_trap_a1": (2, 1, "purple"),
    "maze_trap_a2": (3, 1, "purple"),
    "maze_trap_a3": (4, 1, "purple"),
    "maze_dead_a": (5, 1, "black"),
    "maze_trap_b1": (2, -1, "purple"),
    "maze_trap_b2": (3, -1, "purple"),
    "maze_trap_b3": (4, -1, "purple"),
    "maze_dead_b": (5, -1, "black"),
    "maze_loop1": (2, 2, "brown"),
    "maze_loop2": (3, 2, "brown"),
    "maze_loop3": (4, 2, "brown"),
    "maze_loop4": (5, 2, "brown"),
    "maze_loop5": (6, 2, "brown"),
    "maze_loop6": (6, 1, "brown"),
    "micro_gate1": (7, 0, "orange"),
    "micro_gate2": (8, 0, "orange"),
    "micro_gate3": (9, 0, "orange"),
    "overflow_hell1": (7, 1, "maroon"),
    "overflow_hell2": (8, 1, "maroon"),
    "overflow_hell3": (9, 1, "maroon"),
    "overflow_hell4": (7, -1, "maroon"),
    "overflow_hell5": (8, -1, "maroon"),
    "overflow_hell6": (9, -1, "maroon"),
    "false_hope1": (10, 0, "gold"),
    "false_hope2": (11, 0, "gold"),
    "false_hope3": (12, 0, "gold"),
    "priority_trap1": (10, 1, "gold"),
    "priority_trap2": (11, 1, "gold"),
    "priority_dead": (12, 1, "black"),
    "priority_trap3": (10, -1, "gold"),
    "priority_trap4": (11, -1, "gold"),
    "priority_dead2": (12, -1, "black"),
    "conv_restricted1": (13, 2, "darkred"),
    "conv_restricted2": (14, 2, "darkred"),
    "conv_restricted3": (15, 2, "darkred"),
    "conv_restricted4": (13, 0, "darkred"),
    "conv_restricted5": (14, 0, "darkred"),
    "conv_restricted6": (15, 0, "darkred"),
    "conv_restricted7": (13, -2, "darkred"),
    "conv_restricted8": (14, -2, "darkred"),
    "conv_restricted9": (15, -2, "darkred"),
    "final_merge": (16, 0, "violet"),
    "final_torture1": (17, 0, "crimson"),
    "final_torture2": (18, 0, "crimson"),
    "final_torture3": (19, 0, "crimson"),
    "final_torture4": (20, 0, "crimson"),
    "final_torture5": (21, 0, "crimson"),
    "impossible_goal": (23, 0, "magenta"),
}

# Define edge connections
edges = [
    ("start", "gate_hell1"),
    ("gate_hell1", "gate_hell2"),
    ("gate_hell2", "gate_hell3"),
    ("gate_hell3", "gate_hell4"),
    ("gate_hell4", "gate_hell5"),
    ("gate_hell1", "maze_trap_a1"),
    ("gate_hell2", "maze_trap_b1"),
    ("gate_hell3", "maze_loop1"),
    ("maze_trap_a1", "maze_trap_a2"),
    ("maze_trap_a2", "maze_trap_a3"),
    ("maze_trap_a3", "maze_dead_a"),
    ("maze_trap_b1", "maze_trap_b2"),
    ("maze_trap_b2", "maze_trap_b3"),
    ("maze_trap_b3", "maze_dead_b"),
    ("maze_loop1", "maze_loop2"),
    ("maze_loop2", "maze_loop3"),
    ("maze_loop3", "maze_loop4"),
    ("maze_loop4", "maze_loop5"),
    ("maze_loop5", "maze_loop6"),
    ("maze_loop6", "maze_loop1"),
    ("maze_trap_a2", "micro_gate1"),
    ("maze_trap_b2", "micro_gate1"),
    ("maze_loop3", "micro_gate2"),
    ("gate_hell5", "micro_gate1"),
    ("micro_gate1", "micro_gate2"),
    ("micro_gate2", "micro_gate3"),
    ("micro_gate1", "overflow_hell1"),
    ("micro_gate2", "overflow_hell2"),
    ("micro_gate3", "overflow_hell3"),
    ("micro_gate1", "overflow_hell4"),
    ("micro_gate2", "overflow_hell5"),
    ("micro_gate3", "overflow_hell6"),
    ("overflow_hell1", "overflow_hell2"),
    ("overflow_hell2", "overflow_hell3"),
    ("overflow_hell4", "overflow_hell5"),
    ("overflow_hell5", "overflow_hell6"),
    ("overflow_hell3", "false_hope1"),
    ("overflow_hell6", "false_hope1"),
    ("micro_gate3", "false_hope1"),
    ("false_hope1", "false_hope2"),
    ("false_hope2", "false_hope3"),
    ("false_hope1", "priority_trap1"),
    ("false_hope2", "priority_trap2"),
    ("false_hope3", "priority_dead"),
    ("false_hope1", "priority_trap3"),
    ("false_hope2", "priority_trap4"),
    ("false_hope3", "priority_dead2"),
    ("priority_trap1", "priority_trap2"),
    ("priority_trap3", "priority_trap4"),
    ("false_hope3", "conv_restricted1"),
    ("false_hope3", "conv_restricted4"),
    ("false_hope3", "conv_restricted7"),
    ("conv_restricted1", "conv_restricted2"),
    ("conv_restricted2", "conv_restricted3"),
    ("conv_restricted4", "conv_restricted5"),
    ("conv_restricted5", "conv_restricted6"),
    ("conv_restricted7", "conv_restricted8"),
    ("conv_restricted8", "conv_restricted9"),
    ("conv_restricted3", "final_merge"),
    ("conv_restricted6", "final_merge"),
    ("conv_restricted9", "final_merge"),
    ("final_merge", "final_torture1"),
    ("final_torture1", "final_torture2"),
    ("final_torture2", "final_torture3"),
    ("final_torture3", "final_torture4"),
    ("final_torture4", "final_torture5"),
    ("final_torture5", "impossible_goal"),
    ("overflow_hell1", "conv_restricted1"),
    ("overflow_hell4", "conv_restricted7"),
    ("priority_trap1", "conv_restricted4"),
]

fig, ax = plt.subplots(figsize=(18, 6))

# Plot connections (edges)
for u, v in edges:
    x1, y1, _ = nodes[u]
    x2, y2, _ = nodes[v]
    ax.plot([x1, x2], [y1, y2], color="gray", linewidth=1.2, zorder=1)

# Plot hubs (nodes) and rotated labels
for name, (x, y, color) in nodes.items():
    ax.scatter(x, y, color=color, s=200, edgecolors="black", zorder=2)
    ax.text(x, y + 0.15, name, fontsize=6.5,
            ha="center", va="bottom", rotation=30)

ax.set_title("Challenger Level Graph Visualization")
ax.axis("equal")
ax.grid(True, linestyle="--", alpha=0.3)
plt.tight_layout()
plt.show()
